-- Database: TransitOps

-- DROP DATABASE IF EXISTS "TransitOps";

CREATE DATABASE "TransitOps"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_India.1252'
    LC_CTYPE = 'English_India.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TYPE "vehicle_status" AS ENUM (
  'AVAILABLE',
  'ON_TRIP',
  'IN_SHOP',
  'RETIRED'
);

CREATE TYPE "driver_status" AS ENUM (
  'AVAILABLE',
  'ON_TRIP',
  'OFF_DUTY',
  'SUSPENDED'
);

CREATE TYPE "trip_status" AS ENUM (
  'DRAFT',
  'DISPATCHED',
  'COMPLETED',
  'CANCELLED'
);

CREATE TYPE "maintenance_status" AS ENUM (
  'ACTIVE',
  'COMPLETED'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "role_id" int,
  "created_at" timestamp
);

CREATE TABLE "vehicles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registration_number" varchar UNIQUE,
  "vehicle_name" varchar,
  "vehicle_type" varchar,
  "max_load_capacity" decimal,
  "odometer" decimal,
  "acquisition_cost" decimal,
  "status" vehicle_status,
  "region" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "drivers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "license_number" varchar UNIQUE,
  "license_category" varchar,
  "license_expiry" date,
  "contact_number" varchar,
  "safety_score" decimal,
  "status" driver_status,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "trips" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" int,
  "driver_id" int,
  "source" varchar,
  "destination" varchar,
  "cargo_weight" decimal,
  "planned_distance" decimal,
  "actual_distance" decimal,
  "revenue" decimal,
  "fuel_used" decimal,
  "final_odometer" decimal,
  "status" trip_status,
  "dispatch_time" timestamp,
  "completion_time" timestamp,
  "created_at" timestamp
);

CREATE TABLE "maintenance_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" int,
  "description" text,
  "cost" decimal,
  "status" maintenance_status,
  "start_date" date,
  "end_date" date,
  "created_at" timestamp
);

CREATE TABLE "fuel_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" int,
  "trip_id" int,
  "liters" decimal,
  "cost" decimal,
  "log_date" date,
  "created_at" timestamp
);

CREATE TABLE "expenses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" int,
  "trip_id" int,
  "expense_type" varchar,
  "amount" decimal,
  "description" text,
  "expense_date" date,
  "created_at" timestamp
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar UNIQUE
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trips" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trips" ADD FOREIGN KEY ("driver_id") REFERENCES "drivers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "maintenance_logs" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fuel_logs" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fuel_logs" ADD FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") DEFERRABLE INITIALLY IMMEDIATE;

INSERT INTO roles (role_name)
VALUES
('Fleet Manager'),
('Dispatcher'),
('Safety Officer'),
('Financial Analyst');

INSERT INTO users
(name, email, password_hash, role_id, created_at)
VALUES
(
'Admin',
'admin@transitops.com',
'hashed_password',
1,
CURRENT_TIMESTAMP
);
